" Install VimPlug for Vim
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" utilities
Plug 'scrooloose/nerdtree' " Filesystem explorer
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } } " Fuzzy file finder
Plug 'junegunn/fzf.vim'
Plug 'mileszs/ack.vim' " search inside files using ack. Same as command line ack utility, but use :Ack
Plug 'tpope/vim-surround' " mappings to easily delete, change and add such surroundings in pairs, such as quotes, parens, etc.
Plug 'editorconfig/editorconfig-vim' " .editorconfig support
Plug 'MarcWeber/vim-addon-mw-utils' " interpret a file by function and cache file automatically
Plug 'ervandew/supertab' " Perform all your vim insert mode completions with Tab

" programming language utilities
Plug 'prettier/vim-prettier', { 'do': 'yarn install' } " code formatter
Plug 'tpope/vim-sleuth' " detect indent style (tabs vs. spaces)
Plug 'fatih/vim-go'
Plug 'rust-lang/rust.vim'
Plug 'tpope/vim-endwise' " automatically add end in ruby
Plug 'tpope/vim-ragtag' " endings for html, xml, etc. - enhances surround

" Preview Markdown files in browser with local node server
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install'  }

" Accentuate current line
Plug 'junegunn/limelight.vim'

" Distraction Free Writing
Plug 'junegunn/goyo.vim'


set rtp+=/usr/local/opt/fzf

" Missing or potentially not working options in init.lua
match ErrorMsg '^\(<\|=\|>\)\{7\}\([^=].\+\)\?$'
set backspace=indent,eol,start
set wildmenu
set wildmode=list:longest
set hlsearch

